### ISSUE TITLE
Add to Extension Marketplace?

### ISSUE THREAD

**Issue by christiannaths** [maxlath/vscode-convert-cjs-to-esm#1]
Nice one! This looks to be what I'm after. Just a question: any reason this isn't published to https://marketplace.visualstudio.com/ ? I searched there but couldn't seem to locate it.

**Comment by maxlath** [comment]
It seems that this feature is now part of vscode (see https://stackoverflow.com/questions/69441892/how-to-refactor-all-cjs-files-to-es6-modules-in-all-files-of-a-project-or-direct), which is probably why I stopped using this extension and didn't think it was useful to publish it. I will add that to the readme

**Comment by christiannaths** [comment]
Yeah, that's fair. I think I'd made an incorrect assumption that this extension worked on the entire file... though now I'm not sure where I came up with that assumption 🤔

**Comment by maxlath** [comment]
I haven't tried it, but this package https://www.npmjs.com/package/cjs-to-es6 might be worth a try for full file convertion
